server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fileexchanger}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET:8a2718e2b83ef3083e954556b6a2b8e390c50f806ffad5ed703a830847996c5e}
    expiration-ms: 86400000 # 24 hours
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    access-key: ${S3_ACCESS_KEY:minioadmin}
    secret-key: ${S3_SECRET_KEY:minioadmin}
    bucket-name: ${S3_BUCKET:file-exchanger}
    region: ${S3_REGION:us-east-1}

logging:
  level:
    root: INFO
